version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: 1
      time: "04:00"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore(deps)"
    versioning-strategy: widen

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:30"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(actions)"
